$$color_fg = rgb($HEX__FG)
$$color_bg = rgb($HEX__BG)

$$color_gray = rgb($HEX__BG3)

$$color_dark_black    = rgb($HEX__BLACK)
$$color_dark_red      = rgb($HEX__RED)
$$color_dark_yellow   = rgb($HEX__YELLOW)
$$color_dark_green    = rgb($HEX__GREEN)
$$color_dark_cyan     = rgb($HEX__CYAN)
$$color_dark_blue     = rgb($HEX__BLUE)
$$color_dark_magenta  = rgb($HEX__MAGENTA)
$$color_dark_white    = rgb($HEX__WHITE)

$$color_black         = rgb($HEX__FORE_BLACK)
$$color_red           = rgb($HEX__FORE_RED)
$$color_yellow        = rgb($HEX__FORE_YELLOW)
$$color_green         = rgb($HEX__FORE_GREEN)
$$color_cyan          = rgb($HEX__FORE_CYAN)
$$color_blue          = rgb($HEX__FORE_BLUE)
$$color_magenta       = rgb($HEX__FORE_MAGENTA)
$$color_white         = rgb($HEX__FORE_WHITE)

$$color_link          = rgb($HEX__URL)
