# Basic colors
background              #$HEX__BG
foreground              #$HEX__FG
selection_background    #$HEX__BG3
selection_foreground    #$HEX__FG3
cursor                  #$HEX__FG
cursor_text_color       #000000
url_color               #$HEX__URL


# Windows
active_border_color     #367acd
inactive_border_color   #303030
bell_border_color       #$HEX__FORE_WHITE


# Tabs
tab_bar_background      #$HEX__BG1
inactive_tab_foreground #$HEX__FG
inactive_tab_background #$HEX__BG1
active_tab_foreground   #$HEX__FG
active_tab_background   #$HEX__BG


# Marks
#mark1_foreground
#mark1_background
#mark2_foreground
#mark2_background
#mark3_foreground
#mark3_background


# =========================


# Terminal colors

color0  #$HEX__BLACK
color8  #$HEX__FORE_BLACK

color1  #$HEX__RED
color9  #$HEX__FORE_RED

color2  #$HEX__GREEN
color10 #$HEX__FORE_GREEN

color3  #$HEX__YELLOW
color11 #$HEX__FORE_YELLOW

color4  #$HEX__BLUE
color12 #$HEX__FORE_BLUE

color5  #$HEX__MAGENTA
color13 #$HEX__FORE_MAGENTA

color6  #$HEX__CYAN
color14 #$HEX__FORE_CYAN

color7  #$HEX__WHITE
color15 #$HEX__FORE_WHITE
